language: rust
cache: cargo
rust:
  - nightly
script:
  - rustup default nightly
  - rustup target add wasm32-unknown-unknown
  - cargo uninstall wasm-bindgen-cli || true
  - cargo install wasm-bindgen-cli
  - make