[package]
name = "jrsdparsa"
version = "0.1.0"
authors = ["Nico Grunbaum <na-g@nostrum.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rsdparsa = { git = 'https://github.com/nils-ohlmeier/rsdparsa' }
wasm-bindgen = { git = 'https://github.com/alexcrichton/wasm-bindgen' }
